server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/dev_aub_db
    username: test1
    password: can
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 8
