server:
  port: 9098

spring:
  profiles:
    active: dev
    default: dev

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================
application:
  name: Archivos Umms Backend
  initials: AUB