server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/dev_aub_db
    username: postgres
    password: comoestas
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 8

  flyway:
    locations: classpath:db/migration,classpath:dev/db/migration

